#+TITLE: Synerg(e)ia: A Collaborative - networked live coding interface

Synerg(e)ia (Συνέργεια) is a project for collabotative live coding based in GNU Emacs and SuperCollider

* Why Emacs?

Emacs is free, powerfull, and the best option to start with collaborative livecoding

Synergia uses Emacs Client for collaborative editing

With Emacs Client you do not start a new Emacs instance

In Emacs you can customise your own designs for Networked collaborative live
coding. You can use various tools and to write emacs-lisp to build your own emacs configuration

* Installation

*Prerequisites*

/SuperCollider/

Download SuperCollider here: https://supercollider.github.io/download

/OSCGroups/

How to install oscgroups: https://github.com/RossBencina/oscgroups

*OPENVPN*

Download open-vpn here: https://openvpn.net/download-open-vpn/

*Alternative method - UNIX only*

/Mac/

install open vpn with brew

#+begin_src
brew install openvpn
#+end_src

/Linux/

https://openvpn.net/cloud-docs/openvpn-3-client-for-linux/

* Accessing Synergia

Synergia uses an SSH and OscGroups server located in Greece.

** Connect to Synergia OSCGroups - Emacs-server

*Manually* connection to Synergia server with open-vpn app

To Connect to the server you need to download and intall open-vpn

https://openvpn.net/download-open-vpn/

open openvpn application and upload a user.ovpn

For more information about open-vpn see here: https://openvpn.net/cloud-docs/user-imports-received-profile-into-connect-client/

*Automatically* connection to Synergia server with openvpn command

Open terminal and clone this repository into your =home= directory

#+begin_src
cd ~/ && git clone https://github.com/Vasileios/Synergia-Collaborative-Live-coding.git
#+end_src

To automatically connect to Synergia server with openvpn go to /shell_scrips
folder and run the 1_vpn_connect.sh

If you successfully logged in to the server with open-vpn you are ready to ssh
as user in the server

run the below command to connect via ssh

#+begin_src
ssh user1@192.168.1.51
#+end_src

the password is 'user1' without the quotes ''

If you successfully logged in to the server you can see a terminal window

Go and run the below command on the server's terminal:

Start with emacs-client

#+begin_src
emacstty
#+end_src

if there is no emacs server running run emacs

#+begin_src
emacs
#+end_src

Emacs will run OSCGroupClient and will open an Emacs collaborative live coding session.

** Next step (run oscgroups and supercollider in your machine)

Inside the repository go to =shell_scripts= folder open
=2_oscgroups_sclang_client.sh to edit the path, the username and the password of OSCGroups=

SClang
In The sclang command change the path of sclang if you are using linux or
windows

This will run
OscGroupClient and SuperCollider on your
machine.

** T O D O

create shell scripts

** Run oscgroups in SuperCollider:

Clone sc-hacks-redux repository to your SuperCollider Extensions folder

That contains OSCGroups classes for SuperCollider

https://github.com/iani/sc-hacks-redux

To be able to send osc messages to SuperCollider on the server you will need to edit =OscGroups.sc=

First go and change the oscSendPort to 22243

then go to sendAddress of *init function and change the ip from 127.0.0.1 to 192.168.1.51

#+begin_src
sendAddress = NetAddr("192.168.1.51", oscSendPort);
#+end_src

Save and recompile SuperCollider's class library

Voila!

Now you can switch to Synergia interface to do some collaborative musical live coding

*TIP*: You do not need to create new files to start coding. You can use
the existing buffers usr1_synergia_scws.scd,usr2_synergia_scws.scd, and usr3_synergia_scws.scd instead.

*Have fun!!*
