#+TITLE: Synergia: A Collaborative - networked live coding interface

Synergia is a project for collabotative live coding based in GNU Emacs and SuperCollider

* Why Emacs?

Emacs is free, powerfull, and the best option to start with collaborative livecoding

Synergia uses Emacs Client for collaborative editing

With Emacs Client you do not start a new Emacs instance

In Emacs you can customise your own designs for Networked collaborative live coding
sessions using various tools and emacs-lisp to build your own emacs configuration

* Installation

*Prerequisites*

/SuperCollider/

Download SuperCollider here: https://supercollider.github.io/download

/OSCGroups/

How to install oscgroups: https://github.com/RossBencina/oscgroups

*OPENVPN*

Download open-vpn here: https://openvpn.net/download-open-vpn/

/Mac users/

install open vpn with brew

#+begin_src
brew install openvpn
#+end_src


* Accessing Synergia

Synergia uses an SSH and OscGroups server located in Greece.

** Connect to Syergia OSCGroups - Emacs-server

*Manually* connection to Synergia server with open-vpn app

To Connect to the server you need to download and intall open-vpn

https://openvpn.net/download-open-vpn/

open openvpn application and upload a user.ovpn

For more information about open-vpn see here: https://openvpn.net/cloud-docs/user-imports-received-profile-into-connect-client/


*Automatically* connection to Synergia server with openvpn command

Open terminal and clone this repository into your home directory

To automatically connect to Synergia server with openvpn go to /shell_scrips
folder and run the 1_vpn_connect.sh

If you successfully logged in to the server go and run the
below command on server's terminal:

#+begin_src
emacstty
#+end_src
 if there is no emacs server running run emacs

#+begin_src
emacs
#+end_src

Emacs will run OSCGroupClient and will open an Emacs collaborative live coding session.

** Next step (run oscgroups and supercollider in your unix machine)

Inside the repository go to =shell_scripts= folder and run the
=2_oscgroups_sclang_client.sh=

This will run
OscGroupClient and SuperCollider on your
machine.

_*Jason_comment: at this point the user should edit 1_oscgroups_sclang.sh ==> 1. oscgroups path 2. username oscgroups (otherwise its blocked if 2 users same username) 3. sclang path.
Maybe we should provide instructions for this*_

** Run oscgroups in SuperCollider:

Clone sc-hacks-redux repositiry to your SuperCollider Extensions folder

That contains OSCGroups classes for SuperCollider

https://github.com/iani/sc-hacks-redux

Now you need to edit =OscGroups.sc:=

First go and change the oscSendPort to 22243

then go to sendAddress of *init function and change the ip from 127.0.0.1 to 192.168.1.51

#+begin_src
sendAddress = NetAddr("192.168.1.51", oscSendPort);
#+end_src

Save and recompile SuperCollider's class library

Voila!

Now you can go to synergia interface and start live coding with other users

*TIP*: You do not need to create new files to start coding. You can use
the existed buffers usr1_synergia_scws.scd,usr2_synergia_scws.scd, and usr3_synergia_scws.scd instead.

*Have fun!!*
