#+TITLE: Synergia: A Collaborative - networked live coding interface

Synergia is a project for collabotative live coding in GNU Emacs and SuperCollider

Synergia uses an SSH server located in Greece.


* Installation

*Prerequisites*

/SuperCollider/

Download SuperCollider here: https://supercollider.github.io/download

/OSCGroups/

How to install oscgroups: https://github.com/RossBencina/oscgroups

* Accessing Synergia

First open terminal and Clone this repository into your computer

Then go to shell_scripts folder and run the 1_oscgroups_sclang.sh to run
OSCGroups and SuperCollider on your
machine.

Then read the below to run oscgroups in SupeCollider:

https://github.com/iani/sc-hacks-redux/blob/master/OSCGroups/OscGroupsGuide.org

*Next step* (Connext to server)

Connect to the server from openvpn app and then login with SSH (see [[Connect to server]])

To do this run the 2_after_vpn.sh

If you successfully loged in to the server go to ~/startup directory and run the
below command:

#+begin_src
./process.sh
#+end_src

This will run OSCGroupClient and will open a new tmux widnow.
Now its time to run emacs-shared as a client.

#+begin_src
emacsshare &&
emacstty
#+end_src

Voila!

You can start live coding with other users in SuperCollider

Have fun!!

* T O D O
1. create shell script to open emacs-client and emacs with supercollider workspaces

2. create a startup.scd file to boot the server and to run OscGroups.enable

* Connect to server

To Connect to the server you need to download open-vpn

Then open openvpn application and upload a user.ovpn

For more information about open-vpn see here: https://openvpn.net/cloud-docs/user-imports-received-profile-into-connect-client/

