#+TITLE: Windows Setup: Synerg(e)ia

This will be your guide if you are on Windows.

* Installation

  *Prerequisites*


  *SuperCollider*

  Download SuperCollider here: https://supercollider.github.io/download

  *OSCGroups*

  You can either download OscGroups Windows binaries from here: http://www.rossbencina.com/code/oscgroups

  ... or build from source with MINGW. You can find the source code here: https://github.com/RossBencina/oscgroups

  ... alternatively you can just rely on the binary versions provided with this git repository. OscGroupClient.exe file in the /windows_installation/bin/ folder.

  *OPENVPN*

  Download open-vpn here: https://openvpn.net/download-open-vpn/

** Accessing Synergia

   *Connection to Synergia server with open-vpn app*

   To Connect to the server you need to download and install open-vpn

   https://openvpn.net/download-open-vpn/

   For more information about open-vpn see here: https://openvpn.net/cloud-docs/user-imports-received-profile-into-connect-client/

   Open openvpn application and upload a user.ovpn. Pick one .ovpn file from the current repository in the ovpns folder. Then drag and drop it to the OpenVPN GUI.


** Run oscgroups and supercollider in your machine

   *Configure SuperCollider startup file*

   Open SuperCollider => click on "File" => click "open startup file" and add:
   #+BEGIN_SRC
 s.boot;
 OscGroups.enable;
   #+END_SRC
   Then save and close SuperCollider.

   *Add sclang.exe and scsynth.exe to the PATH system variable*

   If sclang.exe & scsynth.exe are not included in the $PATH variable yet, do one of the following...

   1 via CMD... (open new CMD)
   #+BEGIN_SRC
      setx /M path "%PATH%;C:\path\to\sclang.exe\"
   #+END_SRC
   (it should be somewhere in the Program Files directory, "%PROGRAMFILES%\SuperCollider - your version - \sclang.exe")

   2 ... or via the GUI
   + right click "My Computer"
   + properties
   + advanced settings
   + environment variables
   + system variables
   + choose $PATH
   + edit
   + add
   + paste the full path
   + click "apply" on both opened windows - menus

     *Do this for both sclang.exe & scsynth.exe alternatively you can also add the whole SuperCollider path*.
     *Then !RESTART! current CMD window*

     Finally, run in CMD to check:
     #+BEGIN_SRC
   sclang.exe
     #+END_SRC
     Then Ctrl-c to kill running process.

     *SSH*

     If you successfully logged in to the server with open-vpn you are ready to ssh as user in the server

     run the below command to connect via ssh

     #+begin_src
   ssh user1@10.8.0.1
     #+end_src

     the password is 'user1' without the quotes ''

     If you successfully logged in to the server you will see an emacs scratch buffer.

     You can do =C-x b= (switch-to-buffer) to select usr1, 2, 3 .scd files

     You can now run SuperCollider code with =Shift 2=  If you successfully logged in to the server you can see a terminal window

     Emacs will open an Emacs collaborative live coding session.

** Run oscgroups in SuperCollider:

   To run OSCGroups in SuperCollider you need to install an extension

   clone the below repository into your SuperCollider Extensions folder to run oscgroups in SuperCollider:

   https://github.com/iani/sc-hacks-redux/

   sc-hacks-redux by Iannis Zannos contains OSCGroups classes for SuperCollider (OscGroups and Notification)

   Evaluate the following to see where extensions folder is located

   #+BEGIN_SRC
 Platform.userExtensionDir
   #+END_SRC
   Probably, it will be located in /AppData/Local/SuperCollider .../Extensions/
   To access AppData do: Win keyboard key + R, copy and paste this, then Enter
   #+BEGIN_SRC
%LocalAppData%
   #+END_SRC

   Then, if you downloaded the OscGroups binaries from the official website: unzip the downloaded file to any directory.
   open CMD
   go to the directory where OSCGroups.exe is located via CMD using the "cd" command followed by the path
   e.g. if it is located on the Desktop:
   #+BEGIN_SRC
    cd "%USERPROFILE%\Desktop\oscgroups_win32_2005_06_13_1735"
   #+END_SRC
   then do:
   #+BEGIN_SRC
OscGroupClient.exe 10.8.0.1 22242 22243 22244 22245 username userpass sccolgroup sccolpass
   #+END_SRC

   *Make sure that you edit both username & userpass, they can be ... well whatever you like*

   If you want to run OscGroups on startup put the startup.scd file from
   =client_sclang_config= folder into your SuperCollider Extensions folder

   Recompile class library and boot the server.
   Open a new CMD window and simply do:
#+BEGIN_SRC
sclang.exe
#+END_SRC

   *Voila!*

   Now you can switch to Synergia interface to do some collaborative musical live coding

   *TIP*: You do not need to create new files to start coding. You can use
   the existing buffers usr1_synergia_scws.scd,usr2_synergia_scws.scd, and usr3_synergia_scws.scd instead.

   *Have fun!!*

